# Generated by Django 5.2.14 on 2026-08-25 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofile',
            name='legal_document',
            field=models.CharField(blank=True, help_text='Referencia del documento que acredita la tutela legal (número de acta, expediente, oficio).', max_length=200, verbose_name='Documento de respaldo'),
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardianprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardianships_verified', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
    ]
