# Generated by Django 5.2.14 on 2026-08-28 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0002_guardianprofile_legal_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('PADRE', 'Padre / Madre'), ('TUTOR', 'Tutor legal'), ('ACOMP', 'Acompañante')], default='ACOMP', max_length=50, verbose_name='Relación')),
                ('legal_document', models.CharField(blank=True, help_text='Referencia del documento que acredita la tutela legal (número de acta, expediente, oficio).', max_length=200, verbose_name='Documento de respaldo')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to=settings.AUTH_USER_MODEL, verbose_name='Atleta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardianships_created', to=settings.AUTH_USER_MODEL, verbose_name='Acreditado por')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships_held', to=settings.AUTH_USER_MODEL, verbose_name='Tutor')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardianships_verified', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por')),
            ],
            options={
                'verbose_name': 'Vínculo de tutela',
                'verbose_name_plural': 'Vínculos de tutela',
                'ordering': ['created_at', 'pk'],
                'unique_together': {('athlete', 'guardian')},
            },
        ),
    ]
