# Generated by Django 5.2.14 on 2026-09-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0004_copy_guardianships'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuardianProfile',
        ),
    ]
