#!/usr/bin/env python3
"""Translate django.po ES->EN for Space Cheer using a state-machine parser."""
import os
import subprocess

PO_FILE = r"C:\Users\Lenovo\Documents\SPACE-CHEER\space_cheer\locale\en\LC_MESSAGES\django.po"

TRANSLATIONS = {
    # EVENTS MODELS
    "Motivo del rechazo": "Rejection reason",
    "Borrador": "Draft",
    "Inscripciones abiertas": "Open Registration",
    "Inscripciones cerradas": "Closed Registration",
    "En progreso": "In Progress",
    "Completado": "Completed",
    "Cancelado": "Cancelled",
    "Competencia": "Competition",
    "Taller": "Workshop",
    "Exhibición": "Exhibition",
    "Amistoso": "Friendly",
    "Nombre": "Name",
    "Descripción": "Description",
    "Tipo de evento": "Event type",
    "Estado": "Status",
    "Organizador": "Organizer",
    "Sede": "Venue",
    "Dirección": "Address",
    "Ciudad": "City",
    "Fecha de inicio": "Start date",
    "Fecha de fin": "End date",
    "Apertura de inscripciones": "Registration opens",
    "Cierre de inscripciones": "Registration closes",
    "Máx. equipos": "Max. teams",
    "Banner": "Banner",
    "Evento": "Event",
    "Eventos": "Events",
    "La fecha de fin debe ser igual o posterior a la de inicio.": "The end date must be equal to or after the start date.",
    "El cierre de inscripciones debe ser igual o posterior a la apertura.": "Registration close must be on or after the opening date.",
    "Las inscripciones deben cerrar antes o el mismo día del evento.": "Registration must close before or on the event day.",
    "Categoría de equipo": "Team category",
    "Orden": "Order",
    "Categoría de evento": "Event category",
    "Categorías de evento": "Event categories",
    "Pendiente": "Pending",
    "Aceptado": "Accepted",
    "Rechazado": "Rejected",
    "Retirado": "Withdrawn",
    "Categoría": "Category",
    "Notas": "Notes",
    "Registro de equipo": "Team registration",
    "Registros de equipos": "Team registrations",
    "La categoría no pertenece al evento seleccionado.": "The category does not belong to the selected event.",
    "Atleta": "Athlete",
    "Coach": "Coach",
    "Staff": "Staff",
    "Tutor": "Tutor",
    "Invitado": "Guest",
    "Registrado": "Registered",
    "Confirmado": "Confirmed",
    "Rol": "Role",
    "Participante": "Participant",
    "Participantes": "Participants",
    "El registro de equipo no pertenece al evento seleccionado.": "The team registration does not belong to the selected event.",
    "Activo": "Active",
    "Es rol de juez": "Judge role",
    "Rol de staff": "Staff role",
    "Roles de staff": "Staff roles",
    "Usuario": "User",
    "Asignación de staff": "Staff assignment",
    "Asignaciones de staff": "Staff assignments",
    "Peso": "Weight",
    "Puntaje máximo": "Maximum score",
    "Criterio de evaluación": "Evaluation criterion",
    "Criterios de evaluación": "Evaluation criteria",
    "El peso debe ser mayor a cero.": "The weight must be greater than zero.",
    "El puntaje máximo debe ser mayor a cero.": "The maximum score must be greater than zero.",
    "Preliminar": "Preliminary",
    "Final": "Final",
    "Criterio": "Criterion",
    "Juez": "Judge",
    "Puntaje": "Score",
    "Ronda": "Round",
    "Puntajes": "Scores",
    "El puntaje no puede ser negativo.": "The score cannot be negative.",
    "El puntaje no puede superar el máximo del criterio (%(max)s).": "The score cannot exceed the criterion maximum (%(max)s).",
    "El criterio no pertenece al mismo evento que el registro de equipo.": "The criterion does not belong to the same event as the team registration.",
    "Lugar": "Place",
    "Puntaje total": "Total score",
    "Publicado": "Published",
    "Resultado": "Result",
    "Resultados": "Results",
    "La categoría no pertenece al mismo evento que el registro de equipo.": "The category does not belong to the same event as the team registration.",
    "El lugar debe ser 1 o mayor.": "The place must be 1 or greater.",
    # PRODUCTION
    "Panel de Producción": "Production Panel",
    "Etapas": "Stages",
    "Roles": "Roles",
    "Operarios": "Workers",
    "En producción": "In production",
    "Urgentes": "Urgent",
    "Tareas pendientes": "Pending tasks",
    "Completadas hoy": "Completed today",
    "Todas": "All",
    "Sin asignar": "Unassigned",
    "Urgente": "Urgent",
    "Detalle": "Detail",
    "Quitar urgente": "Remove urgent",
    "Marcar urgente": "Mark urgent",
    "etapas completadas": "completed stages",
    "No hay órdenes en producción.": "No orders in production.",
    "Operarios del sistema": "System workers",
    "Operario": "Worker",
    "Asignado": "Assigned",
    "Quitar": "Remove",
    "Asignar": "Assign",
    "No hay operarios registrados en el sistema.": "No workers registered in the system.",
    "Inactivo": "Inactive",
    "Tareas completadas": "Completed tasks",
    "Roles asignados": "Assigned roles",
    "Última actividad": "Last activity",
    "Editar datos": "Edit data",
    "Apellido": "Last name",
    "Correo": "Email",
    "Guardar cambios": "Save changes",
    "Resetear contraseña": "Reset password",
    "Nueva contraseña": "New password",
    "Mínimo 12 caracteres": "Minimum 12 characters",
    "Cambiar contraseña": "Change password",
    "Desactivar impedirá que el operario inicie sesión.": "Deactivating will prevent the worker from logging in.",
    "Desactivar operario": "Deactivate worker",
    "El operario está desactivado y no puede iniciar sesión.": "The worker is deactivated and cannot log in.",
    "Reactivar operario": "Reactivate worker",
    "Roles de producción": "Production roles",
    "Sin etapas": "No stages",
    "No hay roles de producción configurados.": "No production roles configured.",
    "Crear roles": "Create roles",
    "Últimas 10 tareas completadas": "Last 10 completed tasks",
    "Etapa": "Stage",
    "Producto": "Product",
    "Completada": "Completed",
    "Operarios de Producción": "Production Workers",
    "Crear nuevo operario": "Create new worker",
    "Contraseña temporal": "Temporary password",
    "Crear operario": "Create worker",
    "Operarios activos": "Active workers",
    "Administrar": "Manage",
    "No hay operarios registrados.": "No workers registered.",
    "Operarios desactivados": "Deactivated workers",
    "Ver": "View",
    "Reactivar": "Reactivate",
    "Roles de Producción": "Production Roles",
    "Gestionar etapas": "Manage stages",
    "Nuevo rol": "New role",
    "Nombre del rol": "Role name",
    "Crear": "Create",
    "Sin roles configurados.": "No roles configured.",
    # ACCOUNT
    "Cuenta Inactiva": "Inactive Account",
    "Cuenta desactivada": "Account deactivated",
    "Cuenta inactiva": "Inactive account",
    "Esta cuenta está actualmente inactiva.": "This account is currently inactive.",
    "Contactar soporte": "Contact support",
    "Volver al inicio": "Back to home",
    "¿Crear una nueva cuenta?": "Create a new account?",
    "Registrarse": "Sign Up",
    "Soporte técnico:": "Technical support:",
    "Eliminar dirección": "Delete address",
    "Sí, eliminar": "Yes, delete",
    "Cancelar": "Cancel",
    "Mis direcciones": "My addresses",
    "Editar": "Edit",
    "Nueva": "New",
    "Editar dirección": "Edit address",
    "Nueva dirección": "New address",
    "Tus datos de entrega y correspondencia": "Your delivery and correspondence details",
    "Etiqueta": "Label",
    "Ej: Casa, Trabajo, Gimnasio": "e.g. Home, Work, Gym",
    "Calle, número, colonia": "Street, number, neighborhood",
    "Ej: Guanajuato": "e.g. Guanajuato",
    "C.P.": "Zip code",
    "Usar como dirección principal": "Set as main address",
    "Guardar dirección": "Save address",
    "Mis Direcciones": "My Addresses",
    "Gestiona tus direcciones registradas": "Manage your registered addresses",
    "Nueva Dirección": "New Address",
    "Principal": "Main",
    "CP:": "Zip:",
    "Eliminar": "Delete",
    "Sin direcciones registradas": "No addresses registered",
    "Agrega una dirección para facilitar tus pedidos y envíos.": "Add an address to make your orders and shipments easier.",
    "Agregar primera dirección": "Add first address",
    "Portal de Cuenta": "Account Portal",
    "Importar Atletas": "Import Athletes",
    "Importa múltiples atletas a tu grupo desde un archivo CSV": "Import multiple athletes to your group from a CSV file",
    "Descargar plantilla CSV": "Download CSV template",
    "Subir archivo CSV": "Upload CSV file",
    "Archivo CSV": "CSV file",
    "Máximo 200 atletas por importación. Solo archivos": "Maximum 200 athletes per import. Files only",
    "Codificación: UTF-8 o Latin-1 (Excel compatible).": "Encoding: UTF-8 or Latin-1 (Excel compatible).",
    "Formato del CSV": "CSV format",
    "El archivo debe tener las siguientes columnas en la primera fila:": "The file must have the following columns in the first row:",
    "Columna": "Column",
    "Requerido": "Required",
    "Ejemplo": "Example",
    "Sí": "Yes",
    "No": "No",
    "Resultado de Importación": "Import Result",
    "%(n)s fila(s) procesadas": "%(n)s row(s) processed",
    "Nueva importación": "New import",
    "Importados correctamente": "Successfully imported",
    "Omitidos (ya en tu grupo)": "Skipped (already in your group)",
    "Filas con error": "Rows with errors",
    "Atletas importados (%(n)s)": "Imported athletes (%(n)s)",
    "Nombre completo": "Full name",
    "Filas con error (%(n)s)": "Rows with errors (%(n)s)",
    "Fila": "Row",
    "Nombre en CSV": "Name in CSV",
    "Error": "Error",
    "Descargar plantilla para corregir": "Download template to correct",
    "Los atletas importados reciben el rol": "Imported athletes receive the role",
    "automáticamente y quedan asignados a tu grupo.": "automatically and are assigned to your group.",
    "Cerrar sesión": "Sign out",
    "Este rol requiere validar tu CURP para continuar.": "This role requires validating your CURP to continue.",
    "Validar CURP y Continuar": "Validate CURP and Continue",
    "Salir y completar después": "Exit and complete later",
    "¿Necesitas ayuda para validar tu CURP?": "Need help validating your CURP?",
    "Salir": "Exit",
    "Gestión de Emails": "Email Management",
    "Direcciones de correo electrónico": "Email addresses",
    "Verificado": "Verified",
    "No verificado": "Not verified",
    "Hacer principal": "Make primary",
    "Reenviar verificación": "Resend verification",
    "Advertencia:": "Warning:",
    "Agregar dirección de correo electrónico": "Add email address",
    "Nuevo correo electrónico:": "New email address:",
    "Agregar correo": "Add email",
    "Volver a la cuenta": "Back to account",
    "Confirmar Email": "Confirm Email",
    "Confirmar tu correo electrónico": "Confirm your email address",
    "Confirmar": "Confirm",
    "Este enlace de confirmación de correo electrónico ha expirado o no es válido.": "This email confirmation link has expired or is invalid.",
    "Volver al inicio de sesión": "Back to sign in",
    "¿Problemas con la confirmación?": "Problems with confirmation?",
    "Reenviar confirmación": "Resend confirmation",
    "Asignar Guardián": "Assign Guardian",
    "Para:": "For:",
    "Menor de edad": "Minor",
    "Mayor de edad": "Adult",
    "Volver a Mis Alumnos": "Back to My Students",
    "Si seleccionas otro guardián de la lista y guardas, el actual será": "If you select another guardian from the list and save, the current one will be",
    "reemplazado (Transferencia)": "replaced (Transfer)",
    "Remover Guardián": "Remove Guardian",
    "Guardián registrado": "Registered guardian",
    "Invitar por email": "Invite by email",
    "Selecciona un guardián": "Select a guardian",
    "Adulto": "Adult",
    "Disponible": "Available",
    "Por favor, selecciona un guardián de la lista.": "Please select a guardian from the list.",
    "Tipo de relación": "Relationship type",
    "Opcional: define el vínculo del guardián con el atleta.": "Optional: define the guardian's relationship with the athlete.",
    "Transferir a este Guardián": "Transfer to this Guardian",
    "No hay usuarios adultos disponibles para ser guardians.": "No adult users available to be guardians.",
    "Registra un nuevo usuario": "Register a new user",
    "o usa la pestaña": "or use the tab",
    "Si el padre o tutor": "If the parent or guardian",
    "no tiene cuenta": "has no account",
    "aparecerá en la lista de guardians disponibles.": "they will appear in the list of available guardians.",
    "Email del padre / tutor": "Parent / guardian email",
    "Por favor, ingresa un correo electrónico válido.": "Please enter a valid email address.",
    "Enviar Invitación": "Send Invitation",
    "¿Por qué asignar un guardián?": "Why assign a guardian?",
    "Otros menores pendientes": "Other pending minors",
    "Todos los menores tienen guardian": "All minors have a guardian",
    "Sí, Remover": "Yes, Remove",
    "Panel de Guardian": "Guardian Panel",
    "Alertas activas": "Active alerts",
    "Mis Atletas": "My Athletes",
    "Nacimiento:": "Birth:",
    "Sin fecha de nacimiento": "No birth date",
    "Sin equipo asignado": "No team assigned",
    "Nuevo pedido": "New order",
    "Ver pedidos": "View orders",
    "No tienes atletas asignados bajo tu custodia.": "You have no athletes assigned to your custody.",
    "Gestión de Custodia": "Custody Management",
    "Menores sin guardián asignado": "Minors without assigned guardian",
    "Atención:": "Attention:",
    "Todo en orden.": "All good.",
    "Todos los menores tienen guardián asignado.": "All minors have a guardian assigned.",
    "Gestión de Menores": "Minor Management",
    "Guardián Actual": "Current Guardian",
    "Acción": "Action",
    "Sin Asignar": "Unassigned",
    "Detalles": "Details",
    "Aún no hay atletas menores bajo tu gestión.": "There are no minor athletes under your management yet.",
    "Menores sin Guardián": "Minors without Guardian",
    "Atletas menores de edad que aún no tienen un adulto responsable asignado.": "Minor athletes who do not yet have a responsible adult assigned.",
    "pendiente": "pending",
    "pendientes": "pending",
    "Lista de menores sin guardián": "List of minors without guardian",
    "Fecha de nacimiento": "Birth date",
    "Edad": "Age",
    "Acciones": "Actions",
    "No registrada": "Not registered",
    "Teléfono:": "Phone:",
    "No registrado": "Not registered",
    "Fecha nacimiento:": "Birth date:",
    "Este atleta necesita un guardián para participar en competencias y realizar pedidos.": "This athlete needs a guardian to participate in competitions and place orders.",
    "Asignar ahora": "Assign now",
    "Cerrar": "Close",
    "Acciones masivas": "Bulk actions",
    "Puedes exportar esta lista o enviar recordatorios.": "You can export this list or send reminders.",
    "Exportar CSV": "Export CSV",
    "Enviar recordatorio (próximamente)": "Send reminder (coming soon)",
    "¡No hay menores sin guardián!": "No minors without guardian!",
    "Todos los atletas menores tienen un adulto responsable asignado.": "All minor athletes have a responsible adult assigned.",
    "Ver mis alumnos": "View my students",
    "Recomendación:": "Recommendation:",
    "Iniciar Sesión": "Sign In",
    "Accede a tu cuenta": "Access your account",
    "Correo electrónico o usuario": "Email or username",
    "Contraseña": "Password",
    "Recordar sesión": "Remember me",
    "¿Olvidaste tu contraseña?": "Forgot your password?",
    "O continúa con": "Or continue with",
    "¿No tienes cuenta?": "Don't have an account?",
    "Crear una cuenta nueva": "Create a new account",
    "Powered by": "Powered by",
    "¿Problemas para iniciar sesión?": "Having trouble signing in?",
    "Recuperar contraseña": "Recover password",
    "Cerrar Sesión": "Sign Out",
    "¿Listo para partir?": "Ready to leave?",
    "¿Estás seguro de que deseas cerrar sesión?": "Are you sure you want to sign out?",
    "Sí, cerrar sesión": "Yes, sign out",
    "Cancelar y volver": "Cancel and go back",
    "¿No eres tú?": "Not you?",
    "Inicia sesión con otra cuenta": "Sign in with another account",
    "¿Problemas para cerrar sesión?": "Having trouble signing out?",
    "Contacta a soporte": "Contact support",
    "Contraseña actual": "Current password",
    "Ingresa tu contraseña actual": "Enter your current password",
    "Confirmar nueva contraseña": "Confirm new password",
    "Vuelve a escribir la nueva contraseña": "Re-enter the new password",
    "Restablecer Contraseña": "Reset Password",
    "Recupera tu acceso": "Recover your access",
    "Correo electrónico": "Email address",
    "Enviar enlace de recuperación": "Send recovery link",
    "¿Recordaste tu contraseña?": "Remembered your password?",
    "Inicia sesión": "Sign in",
    "¿Necesitas ayuda?": "Need help?",
    "Ingresa tu nueva contraseña dos veces para verificar.": "Enter your new password twice to verify.",
    "¡Contraseña actualizada!": "Password updated!",
    "Tu contraseña ha sido cambiada exitosamente.": "Your password has been changed successfully.",
    "Ahora puedes iniciar sesión con tu nueva contraseña.": "You can now sign in with your new password.",
    "Iniciar sesión": "Sign in",
    "Establecer contraseña": "Set password",
    "Confirmar contraseña": "Confirm password",
    "Vuelve a escribir la contraseña": "Re-enter the password",
    "Guardar contraseña": "Save password",
    "¿Desactivar tu cuenta?": "Deactivate your account?",
    "Tu cuenta se desactivará inmediatamente y serás desconectado.": "Your account will be deactivated immediately and you will be signed out.",
    "Esto ocurrirá al confirmar:": "This will happen upon confirmation:",
    "No podrás iniciar sesión": "You won't be able to sign in",
    "Tus órdenes activas continuarán": "Your active orders will continue",
    "Tu historial y datos se conservan": "Your history and data are preserved",
    "Tu coach seguirá pudiendo verte": "Your coach will still be able to see you",
    "Escribe": "Type",
    "para continuar": "to continue",
    "Desactivar cuenta": "Deactivate account",
    "Mi Perfil": "My Profile",
    "Eliminar foto": "Delete photo",
    "Cambiar foto": "Change photo",
    "Subir foto": "Upload photo",
    "JPG, PNG o WEBP · Máx. 5 MB": "JPG, PNG or WEBP · Max. 5 MB",
    "Información de cuenta": "Account information",
    "Perfil": "Profile",
    "Completo": "Complete",
    "Incompleto": "Incomplete",
    "CURP": "CURP",
    "Editar perfil": "Edit profile",
    "Nombre(s)": "First name(s)",
    "Apellidos": "Last name(s)",
    "Teléfono": "Phone",
    "Género": "Gender",
    "Actualizar contraseña": "Update password",
    "Zona de peligro": "Danger zone",
    "Configuración": "Settings",
    "Notificaciones y privacidad": "Notifications and privacy",
    "Notificaciones por email": "Email notifications",
    "Guardar": "Save",
    "Privacidad del perfil": "Profile privacy",
    "¿Cuál es tu rol?": "What is your role?",
    "Perfil en revisión": "Profile under review",
    "Guardar y Continuar": "Save and Continue",
    "¿Necesitas ayuda para completar tu perfil?": "Need help completing your profile?",
    "Selecciona tu rol": "Select your role",
    "Continuar": "Continue",
    "Únete a SPACE CHEER": "Join SPACE CHEER",
    "Nombre de usuario": "Username",
    "Acepto los": "I accept the",
    "Términos de servicio": "Terms of service",
    "y": "and",
    "Política de privacidad": "Privacy policy",
    "Crear Cuenta": "Create Account",
    "¿Ya tienes una cuenta?": "Already have an account?",
    "Al registrarte, aceptas nuestros": "By registering, you accept our",
    "Términos": "Terms",
    "Privacidad": "Privacy",
    "Registro temporalmente cerrado": "Registration temporarily closed",
    "No se aceptan nuevos registros en este momento": "No new registrations are accepted at this time",
    "Verificación Enviada": "Verification Sent",
    "Verifica tu correo electrónico": "Verify your email address",
    "¡Revisa tu correo!": "Check your email!",
    "Importante:": "Important:",
    "Si no ves el correo, revisa tu carpeta de spam.": "If you don't see the email, check your spam folder.",
    "¿No recibiste el correo?": "Didn't receive the email?",
    "¿Problemas con la verificación?": "Problems with verification?",
    "Contacta a registro": "Contact registration",
    # COACH
    "Medidas Corporales": "Body Measurements",
    "Volver": "Back",
    "Actual:": "Current:",
    "Guardar todas las medidas": "Save all measurements",
    "Cómo completar las medidas": "How to complete measurements",
    "Usa números decimales con punto (ej: 1.75)": "Use decimal numbers with a period (e.g. 1.75)",
    "Todas las medidas están en centímetros": "All measurements are in centimeters",
    "Deja vacío si no conoces la medida": "Leave blank if you don't know the measurement",
    "Nuevo miembro de crew": "New crew member",
    "Datos del nuevo miembro": "New member data",
    "Datos personales": "Personal data",
    "Email": "Email",
    "correo@ejemplo.com": "email@example.com",
    "Roles y permisos": "Roles and permissions",
    "Rol global": "Global role",
    "Seleccionar rol global…": "Select global role…",
    "Permisos generales en la plataforma.": "General permissions on the platform.",
    "Rol en el equipo": "Team role",
    "Seleccionar rol en equipo…": "Select team role…",
    "Crear y asignar": "Create and assign",
    "Reasignar coach": "Reassign coach",
    "Cambiar el HeadCoach responsable de este usuario": "Change the HeadCoach responsible for this user",
    "Coach actual:": "Current coach:",
    "Nuevo coach": "New coach",
    "Selecciona el nuevo HeadCoach": "Select the new HeadCoach",
    "Seleccionar HeadCoach…": "Select HeadCoach…",
    "actual": "current",
    "El usuario pasará a ser responsabilidad del nuevo HeadCoach.": "The user will become the responsibility of the new HeadCoach.",
    # CORE/BASE
    "Competencias y Uniformes": "Competitions and Uniforms",
    "Inicio": "Home",
    "Panel": "Dashboard",
    "Landing": "Landing",
    "Competencias": "Competitions",
    "Ver Competencias": "View Competitions",
    "Crear Competencia": "Create Competition",
    "Calendario": "Calendar",
    "Mis Registros": "My Registrations",
    "Hospitalidad": "Hospitality",
    "Características": "Features",
    "Mis Estancias": "My Stays",
    "Equipos": "Teams",
    "Mis Equipos": "My Teams",
    "Mis Alumnos": "My Students",
    "Mi Crew": "My Crew",
    "Administración": "Administration",
    "Categorías": "Categories",
    "Campos de medidas": "Measurement fields",
    "Mi Equipo": "My Team",
    "Custodia": "Custody",
    "Menores sin guardian": "Minors without guardian",
    "Tienda": "Store",
    "Catálogo": "Catalog",
    "Productos (admin)": "Products (admin)",
    "Uniformes": "Uniforms",
    "Ofertas": "Offers",
    "Administrar pedidos": "Manage orders",
    "Mis Pedidos": "My Orders",
    "Comunidad": "Community",
    "Invitar": "Invite",
    "Foros": "Forums",
    "Rutinas": "Routines",
    "Red Social": "Social Network",
    "Mi Dashboard": "My Dashboard",
    "Idioma": "Language",
    "Administrar Pedidos": "Manage Orders",
    "Producción": "Production",
    "Mis Tareas": "My Tasks",
    "Panel Admin": "Admin Panel",
    "Especialistas en competencias de cheerleading y venta de uniformes.": "Specialists in cheerleading competitions and uniform sales.",
    "Enlaces": "Links",
    "Soporte": "Support",
    "Ayuda": "Help",
    "Contacto": "Contact",
    "Contáctanos": "Contact us",
    "Todos los derechos reservados.": "All rights reserved.",
    "PRÓXIMO": "UPCOMING",
    # CORE/DASHBOARD
    "Bulk Import": "Bulk Import",
    "Pedidos": "Orders",
    "Mis Equipos Activos": "My Active Teams",
    "Aprobar entrenadores": "Approve coaches",
    "Panel de Custodia": "Custody Panel",
    "Mis equipos": "My teams",
    "Tu cuenta está siendo configurada. Contacta a tu entrenador.": "Your account is being set up. Contact your coach.",
    # CORE/HOME
    "Líderes en Competencias de Cheerleading": "Leaders in Cheerleading Competitions",
    "Eleva tu espíritu con": "Elevate your spirit with",
    "Explorar Competencias": "Explore Competitions",
    "Ver Tienda": "View Store",
    "Atletas": "Athletes",
    "Satisfacción": "Satisfaction",
    "Todo lo que necesitas en un solo lugar": "Everything you need in one place",
    "Explorar": "Explore",
    "Tienda Online": "Online Store",
    "Comprar": "Shop",
    "Academia": "Academy",
    "Aprender": "Learn",
    "Unirse": "Join",
    "Próximas Competencias": "Upcoming Competitions",
    "Ver Todas": "View All",
    "Nacional": "National",
    "Invitación": "Invitation",
    "Festival": "Festival",
    "Uniformes Destacados": "Featured Uniforms",
    "Ver Catálogo": "View Catalog",
    "Lo que dicen nuestros clientes": "What our clients say",
    "Entrenadora": "Coach",
    "Directora": "Director",
    "Crear Cuenta Gratis": "Create Free Account",
    "Saber Más": "Learn More",
    # CUSTODY
    "Cuenta en espera": "Account pending",
    "Si crees que esto es un error, contacta a tu entrenador.": "If you think this is an error, contact your coach.",
    # EVENTS TEMPLATES
    "Categorías y Criterios": "Categories and Criteria",
    "Agregar": "Add",
    "Sin categorías. Agrega la primera.": "No categories. Add the first one.",
    "Máx.": "Max.",
    "Sin criterios. Define cómo se evalúa este evento.": "No criteria. Define how this event is evaluated.",
    "Registros": "Registrations",
    "Equipo": "Team",
    "Registrado por": "Registered by",
    "Fecha": "Date",
    "Aceptar": "Accept",
    "Rechazar": "Reject",
    "Motivo del rechazo (opcional)": "Rejection reason (optional)",
    "No hay registros aún para este evento.": "No registrations yet for this event.",
    "Gestión de Resultados": "Results Management",
    "Calcular puntaje total": "Calculate total score",
    "Equipo registrado": "Registered team",
    "Calcular": "Calculate",
    "Ocultar": "Hide",
    "Publicar": "Publish",
    "Aún no hay resultados calculados. Usa el formulario de arriba.": "No results calculated yet. Use the form above.",
    "Ingresar Scores": "Enter Scores",
    "Nuevo Score": "New Score",
    "Registrar Score": "Register Score",
    "Score": "Score",
    "No hay scores registrados aún.": "No scores registered yet.",
    "Staff y Jueces": "Staff and Judges",
    "Staff General": "General Staff",
    "Jueces": "Judges",
    "Agregar Staff": "Add Staff",
    "Asignar Staff": "Assign Staff",
    "Solo usuarios con rol global STAFF pueden ser asignados aquí.": "Only users with global STAFF role can be assigned here.",
    "Rol en evento": "Event role",
    "Asignado por": "Assigned by",
    "Remover": "Remove",
    "No hay staff asignado aún.": "No staff assigned yet.",
    "Agregar Juez": "Add Judge",
    "Asignar Juez": "Assign Judge",
    "Solo usuarios con rol global JUEZ pueden ser asignados como jueces.": "Only users with global JUDGE role can be assigned as judges.",
    "No hay jueces asignados aún.": "No judges assigned yet.",
    "equipos": "teams",
    "Ver eventos abiertos": "View open events",
    "No tienes equipos activos. Crea o activa tu equipo para poder registrarte en eventos.": "You have no active teams. Create or activate your team to register for events.",
    "Fecha inscripción": "Registration date",
    "Cancelar registro": "Cancel registration",
    "Este registro ya fue aceptado. Al cancelarlo perderás el lugar en el evento.": "This registration was already accepted. Cancelling it will lose your spot in the event.",
    "Sí, cancelar registro": "Yes, cancel registration",
    "No tienes registros en ningún evento.": "You have no registrations in any event.",
    "Buscar eventos abiertos": "Search for open events",
    "Registrar Equipo": "Register Team",
    "¿Qué equipo deseas registrar?": "Which team do you want to register?",
    "Cambiar": "Change",
    "Datos de inscripción": "Registration data",
    "Notas adicionales para los organizadores (opcional)": "Additional notes for organizers (optional)",
    "Confirmar registro": "Confirm registration",
    "Selecciona la categoría en la que competirá tu equipo": "Select the category your team will compete in",
    "Organizado por": "Organized by",
    "Gestionar": "Manage",
    "Gestionar Resultados": "Manage Results",
    "Estancias": "Stays",
    "Mi Estancia": "My Stay",
    "Panel de Juez": "Judge Panel",
    "Confirmar cambio de estado": "Confirm status change",
    "Información del evento": "Event information",
    "Flujo del Evento": "Event Flow",
    "Completa estos pasos para poder": "Complete these steps to",
    "Ir a Categorías y Criterios": "Go to Categories and Criteria",
    "Editar fechas": "Edit dates",
    "Ir a Registros": "Go to Registrations",
    "Ir a Resultados": "Go to Results",
    "Evento completado. No hay más transiciones disponibles.": "Event completed. No more transitions available.",
    "Evento cancelado. No hay más transiciones disponibles.": "Event cancelled. No more transitions available.",
    "No hay transiciones disponibles desde el estado actual.": "No transitions available from the current state.",
    "Límite": "Limit",
    "Los resultados se publicarán próximamente.": "Results will be published soon.",
    "Crear Evento": "Create Event",
    "Editar Evento": "Edit Event",
    "Información general": "General information",
    "Dejar vacío para sin límite": "Leave empty for no limit",
    "Imagen actual — sube una nueva para reemplazarla": "Current image — upload a new one to replace it",
    "Fechas": "Dates",
    "Cuándo abren las inscripciones": "When registrations open",
    "Cuándo cierran las inscripciones": "When registrations close",
    "Explora eventos y competencias disponibles": "Explore available events and competitions",
    "Todos": "All",
    "Próximos": "Upcoming",
    "No hay eventos con este filtro.": "No events with this filter.",
    "Evaluación": "Evaluation",
    "Cat.": "Cat.",
    "No hay equipos aceptados para evaluar.": "No accepted teams to evaluate.",
    "Leaderboard en vivo": "Live leaderboard",
    "Cargando...": "Loading...",
    "Sede por definir": "Venue to be defined",
    "Ver detalle": "View detail",
    # MEASURES
    "Campos de Medidas": "Measurement Fields",
    "Nuevo campo": "New field",
    "Slug": "Slug",
    "Tipo": "Type",
    "Unidad": "Unit",
    "Acciones campo": "Field actions",
    "Habilitar": "Enable",
    "Editar campo": "Edit field",
    "Desactivar campo": "Disable field",
    "Las medidas existentes no se perderán.": "Existing measurements will not be lost.",
    "Desactivar": "Disable",
    "Nuevo campo de medida": "New measurement field",
    # ORDERS
    "Creada:": "Created:",
    "Propietario": "Owner",
    "Creada por": "Created by",
    "Total": "Total",
    "Información de envío": "Shipping information",
    "Nota:": "Note:",
    "Fechas operativas": "Operational dates",
    "Esta orden solo contiene productos simples. No requiere fechas adicionales.": "This order contains only simple products. No additional dates required.",
    "Guardar fechas": "Save dates",
    "Productos": "Products",
    "Talla": "Size",
    "Cantidad": "Quantity",
    "Subtotal": "Subtotal",
    "Atletas:": "Athletes:",
    "Medidas completas": "Complete measurements",
    "Medidas pendientes": "Pending measurements",
    "No hay productos en esta orden": "No products in this order",
    "Progreso de medidas": "Measurement progress",
    "Todas las medidas están completas": "All measurements are complete",
    "Gestión de medidas": "Measurement management",
    "Bloqueadas definitivamente": "Permanently locked",
    "Abiertas": "Open",
    "Cerradas": "Closed",
    "Cerrar medidas": "Close measurements",
    "Reabrir": "Reopen",
    "Bloquear definitivo": "Lock permanently",
    "Diseños": "Designs",
    "Subir nuevo diseño": "Upload new design",
    "Seleccionar imagen": "Select image",
    "Marcar como diseño final": "Mark as final design",
    "Subir": "Upload",
    "Diseño": "Design",
    "Subido por:": "Uploaded by:",
    "Fecha:": "Date:",
    "Estado:": "Status:",
    "No hay diseños subidos aún.": "No designs uploaded yet.",
    "Acciones disponibles": "Available actions",
    "No hay transiciones disponibles en este estado.": "No transitions available in this state.",
    "Historial": "History",
    "No hay eventos registrados.": "No events registered.",
    "Panel de órdenes": "Orders panel",
    "Buscar": "Search",
    "Personal": "Personal",
    "Desde": "From",
    "Hasta": "To",
    "ID": "ID",
    "Dueño": "Owner",
    "Creado por": "Created by",
    "Items": "Items",
    "No hay órdenes": "No orders",
    "Volver a la orden": "Back to order",
    "Configuración incompleta": "Incomplete setup",
    "Detalles del producto": "Product details",
    "Sin descripción": "No description",
    "Precio unitario": "Unit price",
    "Temporada": "Season",
    "Importar atletas": "Import athletes",
    "Eliminar producto": "Delete product",
    "Atletas asignados": "Assigned athletes",
    "Medidas registradas": "Registered measurements",
    "Personalización": "Customization",
    "Medidas": "Measurements",
    "No hay atletas asignados": "No athletes assigned",
    "Debes asignar atletas para configurar este producto": "You must assign athletes to configure this product",
    "Medidas requeridas para este producto": "Required measurements for this product",
    "Medidas de": "Measurements of",
    "Registro de medidas": "Measurement record",
    "La orden no permite modificar medidas.": "The order does not allow modifying measurements.",
    "Este producto no tiene medidas configuradas.": "This product has no configured measurements.",
    "Guardar medidas": "Save measurements",
    "Paginación": "Pagination",
    "Primera": "First",
    "Anterior": "Previous",
    "Siguiente": "Next",
    "Última": "Last",
    "Agregar producto a la orden": "Add product to order",
    "Filtros": "Filters",
    "Tipo de producto": "Product type",
    "Todos los tipos": "All types",
    "Tipo de uso": "Usage type",
    "Todos los usos": "All uses",
    "Todas las temporadas": "All seasons",
    "Rango de precio": "Price range",
    "Mín": "Min",
    "Máx": "Max",
    "Aplicar filtros": "Apply filters",
    "Limpiar filtros": "Clear filters",
    "Buscar productos...": "Search products...",
    "Exclusivo": "Exclusive",
    "Temporada:": "Season:",
    "Medidas requeridas:": "Required measurements:",
    "Tallas disponibles:": "Available sizes:",
    "Precio base": "Base price",
    "No se encontraron productos": "No products found",
    "Intenta con otros filtros o términos de búsqueda": "Try other filters or search terms",
    "No hay productos disponibles": "No products available",
    "No hay productos activos que coincidan con los criterios de esta orden.": "No active products match the criteria for this order.",
    "Agregado": "Added",
    "Información de contacto": "Contact information",
    "Nombre de contacto": "Contact name",
    "Código postal": "Postal code",
    "Guardar contacto": "Save contact",
    "Crear orden": "Create order",
    "Nueva orden de uniformes": "New uniform order",
    "Tipo de orden": "Order type",
    "Selecciona un equipo": "Select a team",
    "No tienes equipos disponibles. Crea un equipo para poder hacer órdenes de equipo.": "You have no available teams. Create a team to place team orders.",
    "Creada el dia:": "Created on:",
    "Borrador — en edición": "Draft — being edited",
    "Agrega los productos que necesites y envía el pedido cuando esté listo.": "Add the products you need and submit the order when it's ready.",
    "Esta orden requiere un pago de congelación antes de poder enviarse.": "This order requires a freeze payment before it can be submitted.",
    "Esta orden no se puede enviar:": "This order cannot be submitted:",
    "Pedido listo para enviarse": "Order ready to submit",
    "Pedido enviado — en revisión": "Order submitted — under review",
    "Tu pedido está siendo revisado. Te notificaremos cuando haya novedades.": "Your order is being reviewed. We'll notify you when there are updates.",
    "Una vez aprobado el diseño, recibirás confirmación para continuar.": "Once the design is approved, you will receive confirmation to continue.",
    "Diseño aprobado": "Design approved",
    "El diseño fue aprobado. Tu pedido entrará en producción próximamente.": "The design was approved. Your order will enter production soon.",
    "Tu pedido está siendo fabricado.": "Your order is being manufactured.",
    "Pedido entregado": "Order delivered",
    "Pedido cancelado": "Order cancelled",
    "Motivo:": "Reason:",
    "Detalles completos": "Full details",
    "Bloqueo de medidas": "Measurement lock",
    "Activado,Desactivado": "Enabled,Disabled",
    "Editable": "Editable",
    "Sí,No": "Yes,No",
    "Fechas importantes": "Important dates",
    "Actualizada:": "Updated:",
    "Diseño aprobado:": "Design approved:",
    "Producción iniciada:": "Production started:",
    "Entregada:": "Delivered:",
    "Cancelada:": "Cancelled:",
    "Fecha límite medidas:": "Measurement deadline:",
    "Fecha entrega uniforme:": "Uniform delivery date:",
    "Pago congelado:": "Freeze payment:",
    "Primer pago:": "First payment:",
    "No hay fechas de eventos registradas": "No event dates registered",
    "Notas de diseño:": "Design notes:",
    "Falta información de contacto:": "Missing contact information:",
    "Por favor, agrega la información de envío para tu orden.": "Please add the shipping information for your order.",
    "Agregar Info": "Add Info",
    "Agregar producto": "Add product",
    "Editar orden": "Edit order",
    "Medidas bloqueadas": "Measurements locked",
    "Ya no es posible modificar las medidas para esta orden.": "Measurements can no longer be modified for this order.",
    "Medidas abiertas": "Measurements open",
    "Puedes agregar o editar tus medidas.": "You can add or edit your measurements.",
    "Medidas cerradas": "Measurements closed",
    "Actualmente no es posible editar medidas.": "It is not currently possible to edit measurements.",
    "Productos en la orden": "Products in the order",
    "producto": "product",
    "Talla:": "Size:",
    "No seleccionada": "Not selected",
    "Seleccionar talla": "Select size",
    "Medidas incompletas": "Incomplete measurements",
    "Configurar": "Configure",
    "más": "more",
    "subtotal": "subtotal",
    "Cant:": "Qty:",
    "Unit:": "Unit:",
    "Gestionar atletas": "Manage athletes",
    "Elegir talla": "Choose size",
    "Total de la orden:": "Order total:",
    "unidades": "units",
    "Esta orden aún no tiene productos": "This order has no products yet",
    "Agrega productos para comenzar": "Add products to start",
    "Sistema": "System",
    "Ver historial completo": "View full history",
    "Enviar pedido": "Submit order",
    "Cancelar pedido": "Cancel order",
    "Aprobar diseño": "Approve design",
    "Iniciar producción": "Start production",
    "Marcar como entregada": "Mark as delivered",
    "Resuelve los problemas señalados arriba": "Resolve the issues listed above",
    "para poder avanzar.": "to proceed.",
    "No hay acciones disponibles": "No actions available",
    "Esta orden ha alcanzado su estado final": "This order has reached its final state",
    "¿Eliminar": "Delete",
    "de la orden?": "from the order?",
    "Notas de diseño y observaciones": "Design notes and observations",
    "Notas de diseño": "Design notes",
    "Instrucciones especiales, colores, personalizaciones...": "Special instructions, colors, customizations...",
    "Estas notas serán visibles para el equipo de producción.": "These notes will be visible to the production team.",
    "Órdenes": "Orders",
    "Estado de la orden": "Order status",
    "Activas": "Active",
    "Finalizadas": "Completed",
    "Mostrando órdenes finalizadas": "Showing completed orders",
    "Mostrando órdenes activas": "Showing active orders",
    "Entregado": "Delivered",
    "Ver detalles": "View details",
    "No hay órdenes finalizadas": "No completed orders",
    "No hay órdenes activas": "No active orders",
    "Comienza creando una nueva orden": "Start by creating a new order",
    "Crear primera orden": "Create first order",
    "Paginación de órdenes": "Order pagination",
    "Cambiar idioma": "Change language",
    # PRODUCTS
    "Sin configurar": "Not configured",
    "Configurado": "Configured",
    "Creado:": "Created:",
    "Inactiva": "Inactive",
    "Sin imagen": "No image",
    "Precios": "Prices",
    "Base:": "Base:",
    "Con variantes:": "With variants:",
    "Precio único": "Single price",
    "Configuración pendiente": "Pending configuration",
    "Este producto requiere configuración antes de poder usarse en órdenes:": "This product requires configuration before it can be used in orders:",
    "Requisitos del producto": "Product requirements",
    "Diseño personalizado": "Custom design",
    "Asignación de atletas": "Athlete assignment",
    "Medidas personalizadas": "Custom measurements",
    "Selección de talla": "Size selection",
    "Equipo específico": "Specific team",
    "Producto protegido": "Protected product",
    "activa": "active",
    "Editar información": "Edit information",
    "Campos bloqueados": "Locked fields",
    "No puede ser modificado o afectaría a órdenes actuales": "Cannot be modified as it would affect current orders",
    "Estrategia de tallas": "Size strategy",
    "Alcance": "Scope",
    "Equipo propietario": "Owner team",
    "Nueva imagen": "New image",
    "Sube una nueva para reemplazar la actual.": "Upload a new one to replace the current.",
    "Tallas": "Sizes",
    "Precio adicional": "Additional price",
    "Agregar talla": "Add size",
    "Precio final": "Final price",
    "Eliminar talla": "Delete size",
    "No hay tallas configuradas.": "No sizes configured.",
    "Campos de medida": "Measurement fields",
    "Campo de medida": "Measurement field",
    "Obligatorio": "Required",
    "Agregar campo": "Add field",
    "No quedan campos disponibles.": "No fields available.",
    "Crear nuevos campos": "Create new fields",
    "Campo": "Field",
    "Eliminar campo de medida": "Delete measurement field",
    "No hay campos configurados.": "No fields configured.",
    "Etapas de producción": "Production stages",
    "Eliminar etapa": "Delete stage",
    "No hay etapas configuradas.": "No stages configured.",
    "Ejemplo:": "Example:",
    "Corrige los siguientes errores:": "Fix the following errors:",
    "Información básica": "Basic information",
    "Estrategia de talla": "Size strategy",
    "Equipo exclusivo": "Exclusive team",
    "Imagen": "Image",
    "JPG, PNG. Máx 5MB.": "JPG, PNG. Max 5MB.",
    "Crear producto": "Create product",
    "Nuevo producto": "New product",
    "Nombre del producto...": "Product name...",
    "Activos": "Active",
    "Inactivos": "Inactive",
    "Limpiar": "Clear",
    "Estrategia": "Strategy",
    "Config.": "Config.",
    "Precio": "Price",
    "Ver / Editar": "View / Edit",
    "No hay productos registrados": "No products registered",
    "Seleccionar tipo de producto": "Select product type",
    "Elige la plantilla que mejor se adapte a tu producto": "Choose the template that best fits your product",
    "Volver a productos": "Back to products",
    "Usar plantilla": "Use template",
    "No hay plantillas disponibles": "No templates available",
    "Contacta con el administrador": "Contact the administrator",
    # SOCIAL
    "Invitar a un amigo": "Invite a friend",
    "Enviar invitación": "Send invitation",
    # TEAMS
    "Unirme a un equipo con código": "Join a team with code",
    "Mi rol": "My role",
    "Coach:": "Coach:",
    "Miembro desde": "Member since",
    "No hay otros miembros activos en este equipo.": "No other active members in this team.",
    "Aún no perteneces a ningún equipo": "You don't belong to any team yet",
    "Pide a tu coach que te agregue o comparte tu código de acceso.": "Ask your coach to add you or share your access code.",
    "Gestión de Categorías de Equipo": "Team Category Management",
    "Crear Categoría": "Create Category",
    "Nivel": "Level",
    "Descripcion": "Description",
    "Eliminar Categoría": "Delete Category",
    "No hay categorías registradas.": "No categories registered.",
    "Editar Categoría": "Edit Category",
    "Guardar Cambios": "Save Changes",
    "Gestión de Equipos": "Team Management",
    "equipo": "team",
    "Crear Equipo": "Create Team",
    "Nuevo": "New",
    "Lista de Equipos": "Team List",
    "Logo": "Logo",
    "Entrenador": "Coach",
    "Código": "Code",
    "Regenerar": "Regenerate",
    "Sin entrenador": "No coach",
    "Miembros": "Members",
    "Gestionar miembros": "Manage members",
    "Regenerar código": "Regenerate code",
    "Editar equipo": "Edit team",
    "No hay equipos registrados": "No teams registered",
    "Comienza creando tu primer equipo.": "Start by creating your first team.",
    "Crear primer equipo": "Create first team",
    "Crear Nuevo Equipo": "Create New Team",
    "Información importante:": "Important information:",
    "El logo debe ser una imagen cuadrada (recomendado 400x400px)": "The logo must be a square image (recommended 400x400px)",
    "La categoría define el nivel competitivo del equipo": "The category defines the team's competitive level",
    "Puedes agregar miembros después de crear el equipo": "You can add members after creating the team",
    "Editar Equipo": "Edit Team",
    "Eliminar Equipo": "Delete Team",
    "¿Estás seguro?": "Are you sure?",
    "Esta acción no se puede deshacer.": "This action cannot be undone.",
    "Todos los miembros serán removidos del equipo.": "All members will be removed from the team.",
    "Eliminar definitivamente": "Delete permanently",
    "Gestión de equipos": "Team management",
    "Desliza horizontalmente para ver más columnas en la tabla": "Swipe horizontally to see more columns in the table",
    "Toca los tres puntos verticales para ver más opciones": "Tap the three vertical dots to see more options",
    "Los badges indican la categoría y ciudad del equipo": "Badges indicate the team's category and city",
    # MISC
    "Equipo:": "Team:",
    "XS, S, M...": "XS, S, M...",
    "Tipo:": "Type:",
    "Uso:": "Use:",
    "Estrategia de talla:": "Size strategy:",
    "Alcance:": "Scope:",
    "Campos definidos por plantilla:": "Fields defined by template:",
    # FORMAT-VARIABLE STRINGS
    "¿Seguro que deseas eliminar la dirección <strong>%(label)s</strong>?": "Are you sure you want to delete the address <strong>%(label)s</strong>?",
    "Asignar Guardián - %(name)s": "Assign Guardian - %(name)s",
    "Guardián Actual: %(name)s": "Current Guardian: %(name)s",
    "Nuevo miembro de crew — %(name)s": "New crew member — %(name)s",
    "Función específica dentro de %(name)s.": "Specific role within %(name)s.",
    "Reasignar coach — %(name)s": "Reassign coach — %(name)s",
    "Bienvenido, %(name)s 👋": "Welcome, %(name)s 👋",
    "Rechazar: %(name)s": "Reject: %(name)s",
    "Scores registrados (%(count)s)": "Registered scores (%(count)s)",
    "Staff asignado (%(count)s)": "Assigned staff (%(count)s)",
    "Jueces asignados (%(count)s)": "Assigned judges (%(count)s)",
    "Equipo: <strong>%(name)s</strong>": "Team: <strong>%(name)s</strong>",
    "Máx. %(n)s equipos": "Max. %(n)s teams",
    "Inscripciones:": "Registrations:",
    "Editar %(name)s": "Edit %(name)s",
    "¿Seguro que deseas desactivar el campo <strong>%(name)s</strong>?": "Are you sure you want to disable the field <strong>%(name)s</strong>?",
    "Orden #%(id)s": "Order #%(id)s",
    "por %(name)s": "by %(name)s",
    "Diseño #%(num)s": "Design #%(num)s",
    "Pasar a %(s)s": "Move to %(s)s",
    "%(count)s atleta": "%(count)s athlete",
    "¿Eliminar <strong>%(name)s</strong> de la orden?": "Delete <strong>%(name)s</strong> from the order?",
    "Orden #%(id)s | Selecciona productos del catálogo": "Order #%(id)s | Select products from catalog",
    "%(count)s producto encontrado": "%(count)s product found",
    "Orden #%(id)s — Datos de envío": "Order #%(id)s — Shipping information",
    "Fecha estimada de entrega: %(date)s": "Estimated delivery date: %(date)s",
    "Tu pedido fue entregado el %(date)s.": "Your order was delivered on %(date)s.",
    "Fecha límite para medidas: %(date)s": "Measurement deadline: %(date)s",
    "Medidas de %(name)s": "Measurements for %(name)s",
    "de %(from)s → %(to)s": "from %(from)s → %(to)s",
    "Editar orden #%(id)s": "Edit order #%(id)s",
    "%(count)s orden encontrada": "%(count)s order found",
    "Usado en %(count)s orden": "Used in %(count)s order",
    "Solo si el alcance es \\": "Only if scope is \\",
    "%(count)s equipo": "%(count)s team",
    "%(count)s compañero": "%(count)s teammate",
    # HOME SAMPLE / LANDING TEXT
    "Uniforme personalizados de alta calidad y accesorios para tu equipo.": "High-quality custom uniforms and accessories for your team.",
    "Conecta con otros equipos, comparte experiencias y crea lazos.": "Connect with other teams, share experiences, and build bonds.",
    "La competencia más prestigiosa del año con equipos de todo el país.": "The most prestigious competition of the year with teams from across the country.",
    "Competencia exclusiva para equipos registrados en nuestra plataforma.": "Exclusive competition for teams registered on our platform.",
    "Festival navideño de cheerleading con categorías para todas las edades.": "Christmas cheerleading festival with categories for all ages.",
    "Diseño espacial con detalles brillantes para competencias.": "Space-inspired design with brilliant details for competitions.",
    "Elegancia y comodidad con nuestro diseño premium.": "Elegance and comfort with our premium design.",
    "Colores vibrantes y diseño moderno para destacar.": "Vibrant colors and modern design to stand out.",
    "Clásico renovado con tecnología de tejido avanzado.": "Classic reimagined with advanced fabric technology.",
    "¿Listo para llevar tu equipo al siguiente nivel?": "Ready to take your team to the next level?",
}


def unescape_po(s):
    """Convert .po string escapes to Python string."""
    return s.replace('\\"', '"').replace('\\n', '\n').replace('\\t', '\t').replace('\\\\', '\\')


def escape_po(s):
    """Convert Python string to .po string escapes."""
    return s.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\t', '\\t')


def translate_po(po_file):
    with open(po_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    output = []
    i = 0
    translated = 0
    skipped = 0

    # Fix header: remove top-level #, fuzzy line
    # and fix Language: field

    while i < len(lines):
        line = lines[i]

        # Remove the standalone fuzzy header flag (line 5: "#, fuzzy\n")
        if line.strip() == '#, fuzzy' and i < 10:
            i += 1
            continue

        # Fix Language: empty -> Language: en
        if '"Language: \\n"' in line:
            line = line.replace('"Language: \\n"', '"Language: en\\n"')
        if '"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"' in line:
            line = line.replace('"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\\n"',
                                '"PO-Revision-Date: 2026-06-19 00:00+0000\\n"')

        # Detect start of a msgid (but not the header msgid "")
        if line.startswith('msgid ') and not line.startswith('msgid ""'):
            # Collect the full msgid value (may span multiple lines)
            msgid_lines = [line]
            raw_val = line.rstrip()[7:-1]  # strip 'msgid "' prefix and trailing '"'
            msgid_val = raw_val  # partial value on this line

            j = i + 1
            # Collect continuation lines
            while j < len(lines) and lines[j].startswith('"'):
                cont = lines[j].rstrip('\n')
                msgid_lines.append(lines[j])
                msgid_val += cont[1:-1]  # strip surrounding quotes
                j += 1

            # Now look for msgstr or msgstr[0]
            # Skip flags/comments between msgid and msgstr
            k = j
            while k < len(lines) and (lines[k].startswith('#') or lines[k].strip() == ''):
                k += 1

            # Check for msgid_plural
            has_plural = False
            plural_lines = []
            if k < len(lines) and lines[k].startswith('msgid_plural '):
                has_plural = True
                plural_lines = [lines[k]]
                k += 1
                while k < len(lines) and lines[k].startswith('"'):
                    plural_lines.append(lines[k])
                    k += 1

            if not has_plural:
                # Regular msgstr
                if k < len(lines) and lines[k].startswith('msgstr "'):
                    msgstr_line = lines[k]
                    msgstr_val = msgstr_line.rstrip()[8:-1]
                    if msgstr_val == '':
                        # Try to translate
                        decoded = unescape_po(msgid_val)
                        if decoded in TRANSLATIONS:
                            translation = escape_po(TRANSLATIONS[decoded])
                            # Write all msgid lines
                            for ml in msgid_lines:
                                output.append(ml)
                            # Write msgstr with translation
                            output.append(f'msgstr "{translation}"\n')
                            translated += 1
                            i = k + 1
                            # Skip continuation lines of msgstr (should be none since we just set it)
                            while i < len(lines) and lines[i].startswith('"'):
                                i += 1
                            continue
                        else:
                            skipped += 1
                            print(f"  SKIP: {repr(decoded[:80])}")
            else:
                # Plural form: msgid + msgid_plural + msgstr[0] + msgstr[1]
                # Check if msgstr[0] is empty
                if k < len(lines) and lines[k].startswith('msgstr[0] ""'):
                    decoded = unescape_po(msgid_val)
                    if decoded in TRANSLATIONS:
                        translation = escape_po(TRANSLATIONS[decoded])
                        for ml in msgid_lines:
                            output.append(ml)
                        for pl in plural_lines:
                            output.append(pl)
                        output.append(f'msgstr[0] "{translation}"\n')
                        output.append(f'msgstr[1] "{translation}"\n')
                        translated += 1
                        i = k + 1
                        # skip msgstr[1] line
                        while i < len(lines) and (lines[i].startswith('msgstr[') or lines[i].startswith('"')):
                            i += 1
                        continue

        output.append(line)
        i += 1

    print(f"Translated: {translated}, Skipped (no translation): {skipped}")

    with open(po_file, 'w', encoding='utf-8') as f:
        f.writelines(output)

    print(f"Written: {po_file}")


if __name__ == '__main__':
    translate_po(PO_FILE)
    mo_path = PO_FILE.replace('.po', '.mo')
    print(f"\nRunning msgfmt -> {mo_path}")
    result = subprocess.run(
        ['msgfmt', '-o', mo_path, PO_FILE],
        capture_output=True, text=True
    )
    print(result.stdout)
    if result.returncode != 0:
        print("STDERR:", result.stderr)
    else:
        print("msgfmt OK — django.mo written")
