# Generated by Django 5.1.7 on 2026-04-13 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_updates', models.BooleanField(default=True)),
                ('email_event_updates', models.BooleanField(default=True)),
                ('email_team_updates', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('PUBLIC', 'Público'), ('TEAM', 'Solo mi equipo'), ('PRIVATE', 'Privado')], default='PRIVATE', max_length=10)),
                ('show_photo', models.BooleanField(default=False)),
                ('show_stats', models.BooleanField(default=True)),
                ('share_measurements_with_judges', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PiiAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('VIEW_CURP', 'Ver CURP'), ('VIEW_MEDICAL', 'Ver datos médicos'), ('VIEW_MEASUREMENTS', 'Ver medidas corporales'), ('VIEW_ADDRESS', 'Ver dirección'), ('EXPORT_DATA', 'Exportar datos'), ('EDIT_PROFILE', 'Editar perfil'), ('BULK_IMPORT', 'Importación masiva')], max_length=30)),
                ('field_accessed', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('accessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_accesses_made', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pii_accesses_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['accessed_by', 'timestamp'], name='accounts_pi_accesse_6923f8_idx'), models.Index(fields=['target_user', 'timestamp'], name='accounts_pi_target__46c740_idx'), models.Index(fields=['access_type', 'timestamp'], name='accounts_pi_access__a4d734_idx')],
            },
        ),
    ]
