# Generated by Django 5.2.8 on 2026-03-13 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userownership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userownership',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator(code='curp_invalida', message='El formato de CURP no es válido.', regex='^[A-Z]{4}\\d{6}[HM](AS|BC|BS|CC|CL|CM|CS|CH|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)[B-DF-HJ-NP-TV-Z]{3}[A-Z0-9]\\d$')]),
        ),
        migrations.AddConstraint(
            model_name='userownership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner', 'user'), name='unique_active_ownership'),
        ),
    ]
