# Generated by Django 5.2.8 on 2025-12-17 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(help_text='Coach dueño del usuario', on_delete=django.db.models.deletion.CASCADE, related_name='owned_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Usuario perteneciente al coach', on_delete=django.db.models.deletion.CASCADE, related_name='owner_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'is_active'], name='accounts_us_owner_i_1d0f58_idx'), models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_436c64_idx')],
                'unique_together': {('owner', 'user')},
            },
        ),
    ]
