# Generated by Django 5.1.7 on 2026-04-18 20:00

import core.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_guardianprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=core.file_utils.user_profile_photo_path, validators=[core.file_utils.validate_image_magic]),
        ),
    ]
