# Generated by Django 5.0.6 on 2026-04-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_judge_type',
            field=models.BooleanField(default=False),
        ),
    ]
