# Generated by Django 5.2.14 on 2026-05-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_is_judge_type_to_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
