# Generated by Django 5.2.14 on 2026-05-18 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_encrypt_existing_pii_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_production_type',
            field=models.BooleanField(default=False),
        ),
    ]
