# Generated by Django 5.0.6 on 2026-06-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_is_production_type_to_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='help_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
