# Generated by Django 5.0.6 on 2026-07-04 03:37

import accounts.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=accounts.fields.EncryptedCharField(help_text='Ciudad', max_length=100, validators=[django.core.validators.RegexValidator("^[A-Za-zÀ-ÿ\\s.'-]+$", "La ciudad solo puede contener letras, espacios y los símbolos . ' -")]),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='zip_code',
            field=accounts.fields.EncryptedCharField(help_text='Código postal', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'El código postal debe tener exactamente 5 dígitos.')]),
        ),
    ]
