# Generated by Django 5.2.14 on 2026-07-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_useraddress_city_alter_useraddress_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Tarea asignada'), ('TASK_COMPLETE', 'Tarea completada'), ('JOB_READY', 'Job listo para entrega'), ('ERROR_REPORTED', 'Error reportado'), ('SOCIAL_LIKE', 'Like a tu publicación'), ('SOCIAL_COMMENT', 'Comentario en tu publicación'), ('SOCIAL_REPOST', 'Compartieron tu publicación')], max_length=30),
        ),
    ]
