# Generated by Django 5.2.14 on 2026-08-14 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_piiaccesslog_access_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piiaccesslog',
            name='access_type',
            field=models.CharField(choices=[('VIEW_CURP', 'Ver CURP'), ('VIEW_MEDICAL', 'Ver datos médicos'), ('VIEW_MEASUREMENTS', 'Ver medidas corporales'), ('EDIT_MEASUREMENTS', 'Editar medidas corporales'), ('VIEW_SIZE', 'Ver talla'), ('EDIT_SIZE', 'Editar talla'), ('VIEW_ADDRESS', 'Ver dirección'), ('EXPORT_DATA', 'Exportar datos'), ('EDIT_PROFILE', 'Editar perfil'), ('BULK_IMPORT', 'Importación masiva')], max_length=30),
        ),
    ]
