# Generated by Django 5.2.14 on 2026-09-02 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_piiaccesslog_access_type'),
        # La copia (custody.0004) lee AthleteProfile.guardian. Sin esta
        # dependencia el campo puede desaparecer ANTES y la copia se lleva
        # cero filas, en silencio y sin vuelta atrás.
        ('custody', '0004_copy_guardianships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athleteprofile',
            name='guardian',
        ),
    ]
