"""
Django settings for space_cheer project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import Csv, config
from csp.constants import NONCE as CSP_NONCE
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


SECRET_KEY = config("SECRET_KEY")

# F — Fernet encryption keys for PII fields (curp, address).
# Generate a key: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Supports key rotation: add new key first, old key(s) after — MultiFernet tries in order.
FERNET_KEYS = config("FERNET_KEYS", cast=Csv())

DEBUG = config("DEBUG", default=False, cast=bool)
AUTH_USER_MODEL = "accounts.User"

ALLOWED_HOSTS = config("ALLOWED_HOSTS", cast=Csv())
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", cast=Csv())
SITE_ID = 2

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Agrega esta línea para habilitar el framework de sitios
    "django.contrib.sites",
    "django_celery_beat",
    # Apps del proyecto
    "teams",
    "measures",
    "core",
    "accounts.apps.AccountsConfig",
    "custody",
    "commerce",
    "events",
    "hospitality",
    "social",
    "orders",
    "products",
    "production.apps.ProductionConfig",
    #
    "widget_tweaks",
    # Allauth
    "allauth",
    "allauth.account",
    # INVITATIONS
    "invitations",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.apple",
]

# =================================================================
# INVITATIONS CONFIGURATION
# =================================================================

# Días antes de que expire la invitación (default=3)
INVITATIONS_INVITATION_EXPIRY = 7

# Si la invitación se acepta después del registro (default=False)
# True: el usuario debe registrarse primero, luego se activa la invitación
INVITATIONS_ACCEPT_INVITE_AFTER_SIGNUP = True

# Prefijo para el asunto (None usa el nombre del sitio entre corchetes)
INVITATIONS_EMAIL_SUBJECT_PREFIX = ""
# =================================================================
# DJANGO ALLAUTH CONFIGURATION
# =================================================================
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_RATE_LIMITS = {
    "login_failed": "5/300s",  # 5 intentos en 300 segundos
}
# ===============IMAGENES==================================
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
# =================================================================

ACCOUNT_LOGOUT_REDIRECT_URL = "/"  # Redirige al home después de logout
ACCOUNT_LOGOUT_ON_GET = False  # Obliga a usar POST para logout (más seguro)
ACCOUNT_LOGOUT_ON_PASSWORD_CHANGE = True  # Invalida otras sesiones al cambiar contraseña
# Redirige a esta URL después de un inicio de sesión exitoso o después de la configuración inicial
LOGIN_REDIRECT_URL = "/"
# settings.py

ACCOUNT_FORMS = {
    "signup": "accounts.forms.CustomSignupForm",
}

ACCOUNT_EMAIL_FIELD = "email"  # Campo de email
ACCOUNT_USER_MODEL_USERNAME_FIELD = "username"  # Campo de username
ACCOUNT_USER_MODEL_EMAIL_FIELD = "email"  # Campo de email en el modelo de usuario

ACCOUNT_EMAIL_VERIFICATION = config("ACCOUNT_EMAIL_VERIFICATION", default="mandatory")
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Space Cheer]"

ACCOUNT_LOGIN_METHODS = {"email", "username"}

ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
# -------------------SOCIALACCOUNT----------------------------
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_ADAPTER = "accounts.adapters.account_adapter.CustomAccountAdapter"

SOCIALACCOUNT_ADAPTER = "accounts.adapters.social_adapter.CustomSocialAccountAdapter"

INVITATIONS_ADAPTER = "accounts.adapters.invitations_adapter.CustomInvitationsAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["email", "profile"],
        "AUTH_PARAMS": {"access_type": "online"},
    }
}

# =================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "accounts.middleware.AdminIPWhitelistMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "csp.middleware.CSPMiddleware",
    "accounts.middleware.PermissionsPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

ROOT_URLCONF = "space_cheer.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "accounts.context_processors.user_roles",
                "social.context_processors.social_bell",
                "orders.context_processors.cart_context",
                "core.context_processors.page_help",
                "core.context_processors.feature_flags",
                "django.template.context_processors.debug",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "space_cheer.wsgi.application"

SESSION_COOKIE_HTTPONLY = True  # JS no puede leer la cookie
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=True, cast=bool)
SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_COOKIE_SAMESITE = "Lax"  # Protección CSRF adicional
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=True, cast=bool)

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        # Mínimo 12 caracteres — plataforma maneja datos de menores (LGDNNA/LFPDPPP)
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es"

LANGUAGES = [
    ("es", "Español"),
    ("en", "English"),
]

LOCALE_PATHS = [BASE_DIR / "locale"]
LANGUAGE_COOKIE_AGE = 365 * 24 * 3600

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

BASE_DIR = Path(__file__).resolve().parent.parent
# TEMPLATES EN UNA SOLA SECCION

CSRF_COOKIE_SAMESITE = "Strict"
CSRF_COOKIE_HTTPONLY = False

# =================================================================
# SECURITY HEADERS (A05 — Security Misconfiguration)
# =================================================================
# Redirige todo el tráfico HTTP a HTTPS. Desactivar solo en desarrollo local.
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=True, cast=bool)

# HSTS: indica al navegador que solo use HTTPS por 1 año
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Requerido para que Django sepa que está detrás de un proxy HTTPS (Nginx).
# Sin esto allauth 65.x devuelve 403 en login y request.is_secure() = False.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Protección contra clickjacking (complementa XFrameOptionsMiddleware)
X_FRAME_OPTIONS = "DENY"

# Evita que el navegador detecte el MIME type por sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# M1 — URL del admin configurable + whitelist de IPs
# En producción: ADMIN_URL=my-secret-admin/ ADMIN_ALLOWED_IPS=1.2.3.4,5.6.7.8
ADMIN_URL = config("ADMIN_URL", default="admin/")
ADMIN_ALLOWED_IPS = config("ADMIN_ALLOWED_IPS", default="", cast=Csv())

# A1 — Content Security Policy
# Nonces habilitados via CSP_INCLUDE_NONCE_IN; 'unsafe-inline' eliminado.
# Todas las etiquetas <style> y <script> inline usan nonce="{{ request.csp_nonce }}".
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        "script-src": [
            "'self'",
            "https://code.jquery.com",
            "https://cdn.datatables.net",
            "https://cdn.jsdelivr.net",
            CSP_NONCE,
        ],
        "style-src": [
            "'self'",
            "https://cdn.datatables.net",
            "https://fonts.googleapis.com",
            CSP_NONCE,
        ],
        "font-src": ["'self'", "data:", "https://fonts.gstatic.com"],
        "img-src": ["'self'", "data:", "blob:"],
        "connect-src": ["'self'"],
        "frame-ancestors": ["'none'"],
        "base-uri": ["'self'"],
        "form-action": ["'self'"],
    }
}

# A4 — Referrer-Policy
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# A4 — Permissions-Policy (leído por PermissionsPolicyMiddleware en accounts/middleware.py)
PERMISSIONS_POLICY = {
    "camera": [],
    "microphone": [],
    "geolocation": [],
}

# A5 — Límite de tamaño para uploads (protege contra DoS por archivos grandes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024   # 5MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024    # 5MB

# =================================================================
# FEATURE FLAGS
# =================================================================
# Previsualización 3D de productos (Three.js). Apagable sin deploy.
PREVIEW_3D_ENABLED = config("PREVIEW_3D_ENABLED", default=True, cast=bool)

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
STATIC_ROOT = BASE_DIR / "staticfiles"

TEMPLATE_DIR = BASE_DIR / "templates"

TEMPLATES[0]["DIRS"] = [TEMPLATE_DIR]

# ==============CELERY CONFIGURATION PARA CELERY===========================
CELERY_BROKER_URL = config("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = config("CELERY_TIMEZONE")
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Acota el intento de conexión al broker al llamar .delay() desde una vista:
# sin esto, una caída de Redis convierte notificaciones "fire and forget" en
# un cuelgue de varios minutos del request (hallazgo 4.5).
CELERY_BROKER_CONNECTION_TIMEOUT = 3
CELERY_BROKER_CONNECTION_MAX_RETRIES = 1
# =========================SMTP PARA ENVÍO DE CORREOS ================================
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT", cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL")

ACCOUNT_EMAIL_SUBJECT_PREFIX = "SPACE CHEER - "


# LOGG
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} [{name}:{lineno}] {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "django.log",
            "formatter": "verbose",
        },
        "error_file": {
            "class": "logging.FileHandler",
            "filename": LOG_DIR / "errors.log",
            "level": "ERROR",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        # Logger específico de tu proyecto (muy importante)
        "space_cheer": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": False,
        },
        # Logger solo para errores críticos
        "django.request": {
            "handlers": ["error_file"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}
