# Generated by Django 5.2.14 on 2026-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='SPACE CHEER', max_length=100, verbose_name='Badge del héroe')),
                ('hero_title', models.CharField(default='Eleva tu espíritu con SPACE CHEER', max_length=200, verbose_name='Título del héroe')),
                ('hero_paragraph', models.TextField(default='La plataforma líder para competencias, entrenamientos y comunidad de cheerleading. Únete a miles de atletas y entrenadores que confían en nosotros.', verbose_name='Párrafo del héroe')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='core/landing/', verbose_name='Imagen del héroe')),
                ('stat1_number', models.CharField(default='500+', max_length=50, verbose_name='Estadística 1 - Número')),
                ('stat1_label', models.CharField(default='Equipos registrados', max_length=50, verbose_name='Estadística 1 - Etiqueta')),
                ('stat2_number', models.CharField(default='50+', max_length=50, verbose_name='Estadística 2 - Número')),
                ('stat2_label', models.CharField(default='Eventos al año', max_length=50, verbose_name='Estadística 2 - Etiqueta')),
                ('stat3_number', models.CharField(default='10K+', max_length=50, verbose_name='Estadística 3 - Número')),
                ('stat3_label', models.CharField(default='Atletas activos', max_length=50, verbose_name='Estadística 3 - Etiqueta')),
                ('cta_title', models.CharField(default='¿Listo para competir?', max_length=200, verbose_name='Título CTA')),
                ('cta_paragraph', models.TextField(default='Regístrate hoy y lleva a tu equipo al siguiente nivel. Inscripciones abiertas para la próxima temporada.', verbose_name='Párrafo CTA')),
            ],
            options={
                'verbose_name': 'Configuración de Landing',
                'verbose_name_plural': 'Configuración de Landing',
            },
        ),
    ]
