[pytest]
DJANGO_SETTINGS_MODULE = space_cheer.settings
python_files = tests.py test_*.py *_tests.py
pythonpath = .

addopts = 
    --reuse-db
    --nomigrations
    --cov=orders
    --cov-report=html
    --cov-report=term-missing:skip-covered
    --maxfail=1
    -v

testpaths = space_cheer/orders/tests