# Generated by Django 5.2.8 on 2026-01-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementfield',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
