# Generated by Django 5.2.8 on 2026-03-11 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measures', '0001_initial'),
        ('products', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('PERSONAL', 'Personal'), ('TEAM', 'Team')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('DESIGN_APPROVED', 'Design approved'), ('IN_PRODUCTION', 'In production'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('measurements_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('design_approved_at', models.DateTimeField(blank=True, null=True)),
                ('design_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed', models.BooleanField(default=False)),
                ('production_started_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('freeze_payment_date', models.DateTimeField(blank=True, null=True)),
                ('first_payment_date', models.DateTimeField(blank=True, null=True)),
                ('measurements_due_date', models.DateField(blank=True, null=True)),
                ('uniform_delivery_date', models.DateField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('design_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_orders', to=settings.AUTH_USER_MODEL)),
                ('owner_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='teams.team')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_create_order', 'Can create order'), ('can_manage_orders', 'Can manage all orders')],
            },
        ),
        migrations.CreateModel(
            name='OrderContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150)),
                ('contact_phone', models.CharField(max_length=20)),
                ('contact_email', models.EmailField(max_length=254)),
                ('shipping_address_line', models.CharField(max_length=255)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_postal_code', models.CharField(max_length=20)),
                ('shipping_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed', models.BooleanField(default=False)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDesignImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/designs/')),
                ('is_final', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_images', to='orders.order')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('size_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productsizevariant')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemAthlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_orders', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='orders.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(max_length=50)),
                ('athlete_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='orders.orderitemathlete')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_unit', models.CharField(blank=True, max_length=20)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('athlete_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='orders.orderitemathlete')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measures.measurementfield')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orders_orde_order_t_d697ad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by'], name='orders_orde_created_780f95_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['owner_user'], name='orders_orde_owner_u_7073bf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['owner_team'], name='orders_orde_owner_t_92524f_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_type', 'PERSONAL'), ('owner_user__isnull', False), ('owner_team__isnull', True)), models.Q(('order_type', 'TEAM'), ('owner_team__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='valid_owner_by_type'),
        ),
        migrations.AddConstraint(
            model_name='orderdesignimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('order',), name='unique_final_design_per_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemathlete',
            index=models.Index(fields=['order_item'], name='orders_orde_order_i_a28c48_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemathlete',
            index=models.Index(fields=['athlete'], name='orders_orde_athlete_972ec5_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitemathlete',
            constraint=models.UniqueConstraint(fields=('order_item', 'athlete'), name='unique_athlete_per_order_item'),
        ),
        migrations.AddConstraint(
            model_name='orderitemmeasurement',
            constraint=models.UniqueConstraint(fields=('athlete_item', 'field'), name='unique_measurement_per_field_per_athlete'),
        ),
        migrations.AddIndex(
            model_name='orderlog',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_f44ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlog',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_b30041_idx'),
        ),
    ]
