# Generated by Django 5.2.8 on 2026-03-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercontactinfo',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='ordercontactinfo',
            name='shipping_address_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordercontactinfo',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ordercontactinfo',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
