# Generated by Django 5.1.7 on 2026-03-31 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measures', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productsizevariant'),
        ),
        migrations.AddField(
            model_name='orderitemathlete',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uniform_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitemathlete',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='orders.orderitem'),
        ),
        migrations.AddField(
            model_name='orderitemcustomization',
            name='athlete_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='orders.orderitemathlete'),
        ),
        migrations.AddField(
            model_name='orderitemmeasurement',
            name='athlete_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='orders.orderitemathlete'),
        ),
        migrations.AddField(
            model_name='orderitemmeasurement',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='measures.measurementfield'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type'], name='orders_orde_order_t_d697ad_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by'], name='orders_orde_created_780f95_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['owner_user'], name='orders_orde_owner_u_7073bf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['owner_team'], name='orders_orde_owner_t_92524f_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('order_type', 'PERSONAL'), ('owner_user__isnull', False), ('owner_team__isnull', True)), models.Q(('order_type', 'TEAM'), ('owner_team__isnull', False), ('owner_user__isnull', True)), _connector='OR'), name='valid_owner_by_type'),
        ),
        migrations.AddConstraint(
            model_name='orderdesignimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_final', True)), fields=('order',), name='unique_final_design_per_order'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemathlete',
            index=models.Index(fields=['order_item'], name='orders_orde_order_i_a28c48_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemathlete',
            index=models.Index(fields=['athlete'], name='orders_orde_athlete_972ec5_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitemathlete',
            constraint=models.UniqueConstraint(fields=('order_item', 'athlete'), name='unique_athlete_per_order_item'),
        ),
        migrations.AddIndex(
            model_name='orderitemmeasurement',
            index=models.Index(fields=['athlete_item'], name='orders_orde_athlete_c55945_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemmeasurement',
            index=models.Index(fields=['field'], name='orders_orde_field_i_1b69e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='orderitemmeasurement',
            constraint=models.UniqueConstraint(fields=('athlete_item', 'field'), name='unique_measurement_per_field_per_athlete'),
        ),
        migrations.AddIndex(
            model_name='orderlog',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_f44ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderlog',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_b30041_idx'),
        ),
    ]
