# Generated by Django 5.2.8 on 2026-03-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_ordercontactinfo_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
