# Generated by Django 5.1.7 on 2026-04-18 20:00

import core.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdesignimage',
            name='image',
            field=models.ImageField(upload_to=core.file_utils.design_upload_path, validators=[core.file_utils.validate_image_magic, core.file_utils.validate_min_size_35mb]),
        ),
    ]
