# Generated by Django 5.2.8 on 2026-03-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_final_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='measurements_open',
            field=models.BooleanField(default=True),
        ),
    ]
