# Generated by Django 5.2.14 on 2026-07-07 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_customer'),
        ('teams', '0002_alter_team_logo_alter_teamsong_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='valid_owner_by_type',
        ),
        migrations.AddField(
            model_name='order',
            name='agreed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('TEAM', 'Team'), ('OFFLINE', 'Personal (offline)')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order_type', 'PERSONAL'), ('owner_user__isnull', False), ('owner_team__isnull', True), ('customer__isnull', True)), models.Q(('order_type', 'TEAM'), ('owner_team__isnull', False), ('owner_user__isnull', True), ('customer__isnull', True)), models.Q(('order_type', 'OFFLINE'), ('customer__isnull', False), ('owner_user__isnull', True), ('owner_team__isnull', True)), _connector='OR'), name='valid_owner_by_type'),
        ),
    ]
