# Generated by Django 5.1.7 on 2026-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0001_initial'),
        ('orders', '0004_order_measurements_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemmeasurement',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitemmeasurement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='orderitemmeasurement',
            name='value_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='orderitemmeasurement',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='orderitemmeasurement',
            index=models.Index(fields=['athlete_item'], name='orders_orde_athlete_c55945_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitemmeasurement',
            index=models.Index(fields=['field'], name='orders_orde_field_i_1b69e7_idx'),
        ),
    ]
