# Generated by Django 5.2.14 on 2026-07-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_valid_owner_by_type_order_agreed_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='custom_measurements',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
