# Generated by Django 5.1.7 on 2026-03-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitemmeasurement_is_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmeasurement',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitemmeasurement',
            name='value_original',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
