# Generated by Django 5.0.6 on 2026-07-06 06:02

import core.file_utils
import django.db.models.deletion
import social.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('avatar', models.ImageField(blank=True, upload_to='social/profiles/avatars/%Y/%m/', validators=[core.file_utils.validate_image_magic, social.models.validate_image_max_5mb])),
                ('cover', models.ImageField(blank=True, upload_to='social/profiles/covers/%Y/%m/', validators=[core.file_utils.validate_image_magic, social.models.validate_image_max_5mb])),
                ('profile_visibility', models.CharField(choices=[('PLATFORM', 'Toda la plataforma'), ('TEAM', 'Solo mi equipo')], default='PLATFORM', max_length=10)),
                ('posts_visibility', models.CharField(choices=[('PLATFORM', 'Toda la plataforma'), ('TEAM', 'Solo mi equipo')], default='PLATFORM', max_length=10)),
                ('hide_activity', models.BooleanField(default=False)),
                ('feed_density', models.CharField(choices=[('COMFORTABLE', 'Cómoda'), ('COMPACT', 'Compacta')], default='COMFORTABLE', max_length=12)),
                ('notify_likes', models.BooleanField(default=True)),
                ('notify_comments', models.BooleanField(default=True)),
                ('notify_reposts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
