# Generated by Django 5.0.6 on 2026-07-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_socialprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='reaction',
            field=models.CharField(choices=[('APPLAUSE', 'Aplausos'), ('FIRE', 'Fuego'), ('STAR', 'Increíble'), ('HEART', 'Me encanta'), ('MUSCLE', 'Ánimo')], default='APPLAUSE', max_length=10),
        ),
    ]
