# Generated by Django 5.2.8 on 2026-03-11 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('measures', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('product_type', models.CharField(choices=[('UNIFORM', 'Uniforme'), ('SHOES', 'Tenis'), ('BAG', 'Mochila'), ('OTHER', 'Otro')], max_length=20)),
                ('usage_type', models.CharField(choices=[('GLOBAL', 'Global'), ('TEAM_CUSTOM', 'Personalizado por equipo'), ('ATHLETE_CUSTOM', 'Personalizado por atleta')], max_length=20)),
                ('scope', models.CharField(choices=[('CATALOG', 'Catálogo'), ('TEAM_ONLY', 'Solo un equipo')], default='CATALOG', max_length=20)),
                ('size_strategy', models.CharField(choices=[('NONE', 'No usa tallas'), ('STANDARD', 'Tallas estándar'), ('MEASUREMENTS', 'Medidas personalizadas')], default='NONE', max_length=20)),
                ('is_configured', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/images/')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_team', models.ForeignKey(blank=True, help_text='Equipo dueño si el producto es exclusivo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exclusive_products', to='teams.team')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.season')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMeasurementField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.measurementfield')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_fields', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'field'), name='unique_product_measurement_field')],
            },
        ),
        migrations.CreateModel(
            name='ProductSizeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_variants', to='products.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'size'), name='unique_product_size')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['usage_type'], name='products_pr_usage_t_64bd62_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['scope'], name='products_pr_scope_015c23_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['size_strategy'], name='products_pr_size_st_f37d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='products_pr_is_acti_ca4d9a_idx'),
        ),
    ]
