# Generated by Django 5.1.7 on 2026-04-18 20:00

import core.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.file_utils.product_image_path, validators=[core.file_utils.validate_image_magic]),
        ),
    ]
