# Generated by Django 5.0.6 on 2026-07-05 02:02

import core.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_3d',
            field=models.FileField(blank=True, help_text='Modelo 3D en formato .glb (máx 15 MB). Genéralo con Tripo AI o Meshy desde fotos del producto.', null=True, upload_to=core.file_utils.product_model3d_path, validators=[core.file_utils.validate_glb_magic, core.file_utils.validate_glb_max_15mb]),
        ),
    ]
