# Generated by Django 5.2.14 on 2026-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_model_3d'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_on_landing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='landing_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
