# Generated by Django 5.2.14 on 2026-07-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_featured_on_landing_product_landing_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='scope',
            field=models.CharField(choices=[('CATALOG', 'Catálogo'), ('TEAM_ONLY', 'Solo un equipo'), ('INTERNAL', 'Interno (taller)')], default='CATALOG', max_length=20),
        ),
    ]
