# Generated by Django 5.0.6 on 2026-04-18 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Característica de habitación',
                'verbose_name_plural': 'Características de habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospitality/hotels/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='events.event')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hospitality.hotel')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('SINGLE', 'Individual'), ('DOUBLE', 'Doble'), ('QUEEN', 'Queen'), ('KING', 'King'), ('BUNK', 'Litera')], default='SINGLE', max_length=20)),
                ('label', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='hospitality.room')),
            ],
            options={
                'verbose_name': 'Cama',
                'verbose_name_plural': 'Camas',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('features', models.ManyToManyField(blank=True, related_name='room_types', to='hospitality.roomfeature')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_types', to='hospitality.hotel')),
            ],
            options={
                'verbose_name': 'Tipo de habitación',
                'verbose_name_plural': 'Tipos de habitaciones',
                'unique_together': {('hotel', 'name')},
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hospitality.roomtype'),
        ),
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('CONFIRMED', 'Confirmado'), ('CHECKED_IN', 'Check-in realizado'), ('CHECKED_OUT', 'Check-out realizado'), ('CANCELLED', 'Cancelado')], default='REQUESTED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stays_created_by_me', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stays', to='events.event')),
                ('event_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stay', to='events.eventparticipant')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitality.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_stays', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estancia',
                'verbose_name_plural': 'Estancias',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hospitality.room')),
                ('stay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignment', to='hospitality.stay')),
            ],
            options={
                'verbose_name': 'Asignación de habitación',
                'verbose_name_plural': 'Asignaciones de habitaciones',
            },
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'room_number')},
        ),
        migrations.CreateModel(
            name='HospitalityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_needs', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('event_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.eventparticipant')),
                ('roommate_preferences', models.ManyToManyField(blank=True, related_name='roommate_requested_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('preferred_hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitality.hotel')),
                ('preferred_features', models.ManyToManyField(blank=True, related_name='preferences', to='hospitality.roomfeature')),
                ('preferred_room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospitality.roomtype')),
            ],
            options={
                'verbose_name': 'Preferencia de hospitalidad',
                'verbose_name_plural': 'Preferencias de hospitalidad',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='BedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hospitality.bed')),
                ('stay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_assignments', to='hospitality.stay')),
            ],
            options={
                'verbose_name': 'Asignación de cama',
                'verbose_name_plural': 'Asignaciones de camas',
                'unique_together': {('stay', 'bed')},
            },
        ),
    ]
