# Generated by Django 5.0.6 on 2026-05-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'room_number', 'floor')},
        ),
    ]
