# Generated by Django 5.2.14 on 2026-08-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitality', '0002_room_unique_number_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Cuántas personas duermen en esta cama. Vacío = el default de su tipo (individual 1, el resto 2). Úsalo para una matrimonial angosta o una litera de tres.', null=True, verbose_name='Capacidad'),
        ),
    ]
