# Generated by Django 5.1.7 on 2026-03-31 15:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=0, help_text='Nivel jerárquico (0 = base, mayor = más alto)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['level', 'name'],
                'unique_together': {('name', 'level')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('join_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coach', models.ForeignKey(help_text='Entrenador principal del equipo', on_delete=django.db.models.deletion.CASCADE, related_name='coached_teams', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.teamcategory')),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la canción / pista', max_length=200)),
                ('audio', models.FileField(upload_to='teams/songs/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden dentro de la lista (0 = primero)')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='teams.teamcategory')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='teams.team')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('team', 'category', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_team', models.CharField(choices=[('ATHLETE', 'ATHLETE'), ('COACH', 'Coach'), ('STAFF', 'Staff')], default='ATHLETE', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado'), ('inactive', 'Inactivo')], default='pending', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_joined'],
                'unique_together': {('user', 'team')},
            },
        ),
    ]
