# Generated by Django 5.1.7 on 2026-03-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteammembership',
            name='role_in_team',
            field=models.CharField(choices=[('ATLETA', 'Atleta'), ('COACH', 'Coach'), ('STAFF', 'Staff')], default='ATLETA', max_length=20),
        ),
    ]
