# Generated by Django 5.2.8 on 2025-12-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
