# Generated by Django 5.0.6 on 2026-04-18 19:53

import core.file_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.file_utils.team_photo_path, validators=[core.file_utils.validate_image_magic]),
        ),
        migrations.AlterField(
            model_name='teamsong',
            name='audio',
            field=models.FileField(upload_to=core.file_utils.team_song_path, validators=[core.file_utils.validate_audio_magic]),
        ),
    ]
