# Generated by Django 5.2.8 on 2026-01-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_city_alter_team_logo_alter_team_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteammembership',
            name='role_in_team',
            field=models.CharField(choices=[('ATLETA', 'Atleta'), ('HEADCOACH', 'Head Coach'), ('COACH', 'Coach'), ('STAFF', 'Staff')], default='member', max_length=20),
        ),
    ]
