# Generated by Django 5.2.8 on 2026-01-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_userteammembership_role_in_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userteammembership',
            name='role_in_team',
            field=models.CharField(choices=[('ATLETA', 'Atleta'), ('COACH', 'Coach'), ('STAFF', 'Staff')], default='member', max_length=20),
        ),
    ]
