# Generated by Django 5.2.14 on 2026-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiontask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
