# Generated by Django 5.0.6 on 2026-06-23 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_add_production_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstageconfig',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_configs', to='production.productionstage'),
        ),
    ]
