# Generated by Django 5.2.14 on 2026-07-06 18:36

from django.db import migrations, models


def backfill_job_status(apps, schema_editor):
    """Deriva el estado de los jobs existentes a partir de sus datos.

    - completed_at seteado → COMPLETED
    - alguna task completada (sin terminar el job) → IN_PROGRESS
    - resto → PENDING (default del campo)
    """
    ProductionJob = apps.get_model('production', 'ProductionJob')

    ProductionJob.objects.filter(completed_at__isnull=False).update(
        status='COMPLETED'
    )
    in_progress_ids = ProductionJob.objects.filter(
        completed_at__isnull=True,
        tasks__status='COMPLETED',
    ).values_list('pk', flat=True).distinct()
    ProductionJob.objects.filter(pk__in=list(in_progress_ids)).update(
        status='IN_PROGRESS'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_productstageconfig_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('PAUSED', 'Pausado'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20),
        ),
        migrations.RunPython(backfill_job_status, migrations.RunPython.noop),
    ]
