# Generated by Django 5.0.6 on 2026-04-18 19:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0002_alter_team_logo_alter_teamsong_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventStaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('COMPETITION', 'Competition'), ('WORKSHOP', 'Workshop'), ('EXHIBITION', 'Exhibition'), ('FRIENDLY', 'Friendly')], default='COMPETITION', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REGISTRATION_OPEN', 'Registration Open'), ('REGISTRATION_CLOSED', 'Registration Closed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('venue_name', models.CharField(blank=True, max_length=200)),
                ('venue_address', models.CharField(blank=True, max_length=300)),
                ('venue_city', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_open', models.DateField(blank=True, null=True)),
                ('registration_close', models.DateField(blank=True, null=True)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='events.event')),
                ('team_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_categories', to='teams.teamcategory')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventJudgingCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judging_criteria', to='events.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_staff_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='events.eventstaffrole')),
            ],
        ),
        migrations.CreateModel(
            name='EventTeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.eventcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_registrations', to='events.event')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_registrations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_registrations', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='EventScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('round', models.CharField(choices=[('PRELIMINARY', 'Preliminary'), ('FINAL', 'Final')], default='FINAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='events.eventjudgingcriteria')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_given', to=settings.AUTH_USER_MODEL)),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.eventteamregistration')),
            ],
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.PositiveIntegerField()),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('round', models.CharField(choices=[('PRELIMINARY', 'Preliminary'), ('FINAL', 'Final')], default='FINAL', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='events.eventcategory')),
                ('team_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.eventteamregistration')),
            ],
            options={
                'ordering': ['placement'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ATHLETE', 'Athlete'), ('COACH', 'Coach'), ('STAFF', 'Staff'), ('GUARDIAN', 'Guardian'), ('GUEST', 'Guest')], default='ATHLETE', max_length=20)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='REGISTERED', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to=settings.AUTH_USER_MODEL)),
                ('team_registration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='events.eventteamregistration')),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status'], name='events_even_status_5709b6_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organizer'], name='events_even_organiz_266ef7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventcategory',
            unique_together={('event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='eventjudgingcriteria',
            unique_together={('event', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='eventstaffassignment',
            unique_together={('event', 'user', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='eventteamregistration',
            unique_together={('event', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='eventscore',
            unique_together={('team_registration', 'criteria', 'judge', 'round')},
        ),
        migrations.AlterUniqueTogether(
            name='eventresult',
            unique_together={('team_registration', 'category', 'round')},
        ),
        migrations.AlterUniqueTogether(
            name='eventparticipant',
            unique_together={('event', 'user')},
        ),
    ]
