# Generated by Django 5.0.6 on 2026-04-21 14:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('teams', '0002_alter_team_logo_alter_teamsong_audio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoría de evento', 'verbose_name_plural': 'Categorías de evento'},
        ),
        migrations.AlterModelOptions(
            name='eventjudgingcriteria',
            options={'ordering': ['order'], 'verbose_name': 'Criterio de evaluación', 'verbose_name_plural': 'Criterios de evaluación'},
        ),
        migrations.AlterModelOptions(
            name='eventparticipant',
            options={'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='eventresult',
            options={'ordering': ['placement'], 'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.AlterModelOptions(
            name='eventscore',
            options={'verbose_name': 'Puntaje', 'verbose_name_plural': 'Puntajes'},
        ),
        migrations.AlterModelOptions(
            name='eventstaffassignment',
            options={'verbose_name': 'Asignación de staff', 'verbose_name_plural': 'Asignaciones de staff'},
        ),
        migrations.AlterModelOptions(
            name='eventstaffrole',
            options={'ordering': ['name'], 'verbose_name': 'Rol de staff', 'verbose_name_plural': 'Roles de staff'},
        ),
        migrations.AlterModelOptions(
            name='eventteamregistration',
            options={'verbose_name': 'Registro de equipo', 'verbose_name_plural': 'Registros de equipos'},
        ),
        migrations.AddField(
            model_name='eventstaffrole',
            name='is_judge',
            field=models.BooleanField(default=False, verbose_name='Es rol de juez'),
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('COMPETITION', 'Competencia'), ('WORKSHOP', 'Taller'), ('EXHIBITION', 'Exhibición'), ('FRIENDLY', 'Amistoso')], default='COMPETITION', max_length=20, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Máx. equipos'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='Organizador'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_close',
            field=models.DateField(blank=True, null=True, verbose_name='Cierre de inscripciones'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_open',
            field=models.DateField(blank=True, null=True, verbose_name='Apertura de inscripciones'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('REGISTRATION_OPEN', 'Inscripciones abiertas'), ('REGISTRATION_CLOSED', 'Inscripciones cerradas'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado')], default='DRAFT', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sede'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='max_teams',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Máx. equipos'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='team_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_categories', to='teams.teamcategory', verbose_name='Categoría de equipo'),
        ),
        migrations.AlterField(
            model_name='eventjudgingcriteria',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventjudgingcriteria',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='eventjudgingcriteria',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5, verbose_name='Puntaje máximo'),
        ),
        migrations.AlterField(
            model_name='eventjudgingcriteria',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='eventjudgingcriteria',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='eventjudgingcriteria',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('ATHLETE', 'Atleta'), ('COACH', 'Coach'), ('STAFF', 'Staff'), ('GUARDIAN', 'Tutor'), ('GUEST', 'Invitado')], default='ATHLETE', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registrado'), ('CONFIRMED', 'Confirmado'), ('CANCELLED', 'Cancelado')], default='REGISTERED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='events.eventcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='placement',
            field=models.PositiveIntegerField(verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='round',
            field=models.CharField(choices=[('PRELIMINARY', 'Preliminar'), ('FINAL', 'Final')], default='FINAL', max_length=20, verbose_name='Ronda'),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Puntaje total'),
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='events.eventjudgingcriteria', verbose_name='Criterio'),
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores_given', to=settings.AUTH_USER_MODEL, verbose_name='Juez'),
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='round',
            field=models.CharField(choices=[('PRELIMINARY', 'Preliminar'), ('FINAL', 'Final')], default='FINAL', max_length=20, verbose_name='Ronda'),
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Puntaje'),
        ),
        migrations.AlterField(
            model_name='eventscore',
            name='team_registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='events.eventteamregistration', verbose_name='Registro de equipo'),
        ),
        migrations.AlterField(
            model_name='eventstaffassignment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='eventstaffassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='events.eventstaffrole', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='eventstaffassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_staff_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='eventstaffrole',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventstaffrole',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='eventstaffrole',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='eventteamregistration',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.eventcategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='eventteamregistration',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='eventteamregistration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('WITHDRAWN', 'Retirado')], default='PENDING', max_length=20, verbose_name='Estado'),
        ),
    ]
