# Generated by Django 5.2.14 on 2026-07-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_is_judge_to_eventstaffrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='role',
            field=models.CharField(choices=[('ATHLETE', 'Atleta'), ('HEADCOACH', 'Head Coach'), ('COACH', 'Coach'), ('STAFF', 'Staff'), ('GUARDIAN', 'Tutor'), ('GUEST', 'Invitado')], default='ATHLETE', max_length=20, verbose_name='Rol'),
        ),
    ]
