# Generated by Django 5.2.14 on 2026-07-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventparticipant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='featured_on_landing',
            field=models.BooleanField(default=False, verbose_name='Destacado en landing'),
        ),
        migrations.AddField(
            model_name='event',
            name='landing_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden en landing'),
        ),
    ]
